
[slack]
token = "xoxb-7417263271732-7957682213092-Gy70XhpkYuCUfiH2eDgJqrb9"
channelID = "C07U35JUM1Q"

[cryptoCurrency.binance]
APIHeaderKey= "X-MBX-APIKEY"
APIKey = "EHwDGGSMka24Sik6R8pl52u392nKuv4sWvBtFwok3JLqIp8guZNjJbxXwri9CERL"
SecretKey = ""




#
#type Config struct {
#Slack          Slack
#CryptoCurrency []CryptoCurrency
#}

#https://api.binance.com
#yExqHR3bzWSQK2vVg48qxFVnEPzTuRHhhZkYjMSMjRPIqivcFkksW4c9PS1Uoamk

#GsXbZWfGiZrVpIZLtHDbgTt3Pdpr3q0jfoP0REXLYR7PAAc490ylROlISuhJytyS